version: '3.8'

services:
  
  app:
    build: .
    container_name: quizzes
    ports:
      - "4000:8088"  
    environment:
      - DB_HOST=db
      - DB_PORT=4000
      - DB_USERNAME=postgres
      - DB_PASSWORD=123456
      - DB_NAME=quizzes
      - JWT_SECRET=jwt-secret
    depends_on:
      - db
    networks:
      - quizzes-network

 
  db:
    image: postgres:13
    container_name: trivia-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: quizzes
    ports:
      - "5432:5432"  
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - quizzes-network


volumes:
  postgres-data:


networks:
  trivia-network: