version: '3.8'

services:
  app:
    build: .
    container_name: container-quizzes
    ports:
      - "4000:4000"  
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=123456
      - DB_NAME=quizzes
      - JWT_SECRET=jwt-secret
    depends_on:
      - db
    networks:
      - trivia-network

  db:
    image: postgres:13
    container_name: container-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: quizzes
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - trivia-network

volumes:
  postgres-data:

networks:
  trivia-network:
